module DatsHelper

	def convert_ks2_to_a_score(ks2)
		 @ks2_number = {"W"=> 0, "1C" => 1, "1B" => 2, "1A" => 3, "2C" => 4, "2B" => 5, "2A" => 6, "3C" => 7, 
		 				"3B" => 8, "3A" => 9, "4C" => 10, "4B" => 11, "4A" => 12,  "5C" => 13, "5B" => 14,
    					"5A" => 15, "6C" => 16, "6B" => 17, "6A" => 18}
    				
    	return @ks2_number[ks2.upcase]
    				
	end
	
	#Takes info to calculate levels of progress made
	def calculate_levels_of_progess(eng_ks2, math_ks2, subject_title, point_score)
		subject = check_subject(subject_title[0..-14].gsub(/-/, ' '))
		if subject == 'maths'
			ks2_score = convert_ks2_to_a_score(math_ks2)
		elsif subject == 'english'
			ks2_score = convert_ks2_to_a_score(eng_ks2)
		else
			eng = convert_ks2_to_a_score(eng_ks2)
			math = convert_ks2_to_a_score(math_ks2)
			ks2_score = (eng+math)/2
		end
		if point_score && ks2_score
			return (2+(point_score.to_f - ks2_score.to_f/3)).round(2)
		end
	end


	# Convert the grade to the correct number 
	# This still needs adapting to cover the different level 1 and level 2 /BTEC Cambridge Nationals Scores
	
	def convert_grade_to_number(subject_title, grade)
		
		@grade_score = {"U" => 0, "G"=>1, "F"=>2, "E"=>3, "D"=>4, "C" => 5, "B" => 6, "A" => 7, "A*"=>8}
		btec_score ={"PASS" => 5, "MERIT" => 6, "DISTINCTION" => 7, "DISTINCTION*" =>8}
    	l2n_1_score ={"PASS" => 1.5, "MERIT" => 3, "DISTINCTION" => 4}
    	l2n_2_score ={"PASS" => 5, "MERIT" => 6, "DISTINCTION" => 7, "DISTINCTION*" =>8}
    	
		if ['maths','english','english_lit','science','humanities','language'].include? check_subject(subject_title) 
		return @grade_score[grade.upcase]
		elsif check_subject(subject_title) == 'other'
		return btec_score[grade.upcase]
		end
	end
	
	# Check the subject 
	def check_subject(subject_title)
	
			
		maths =['AQA Level 3 Advanced Subsidiary GCE in Mathematics', 
		'Pearson Edexcel Level 3 Advanced Subsidiary GCE in Mathematics', 
		'OCR Advanced Subsidiary GCE in Mathematics ', 
		'WJEC Advanced Subsidiary GCE in Mathematics', 
		'CCEA Advanced Subsidiary GCE in Mathematics', 
		'OCR Advanced Subsidiary GCE in Mathematics', 
		'CCEA Level 1 or Level 2 GCSE in Mathematics Pilot', 
		'AQA Level 1 or Level 2 GCSE in Mathematics A', 
		'AQA Level 1 or Level 2 GCSE in Mathematics B', 
		'EDEXCEL Level 1 or Level 2 GCSE in Mathematics A', 
		'EDEXCEL Level 1 or Level 2 GCSE in Mathematics B', 
		'OCR Level 1 or Level 2 GCSE in Mathematics A', 
		'OCR Level 1 or Level 2 GCSE in Mathematics B', 
		'OCR Level 1 or Level 2 GCSE in Mathematics C', 
		'WJEC Level 1 or Level 2 GCSE in Mathematics', 
		'AQA Level 1 or Level 2 GCSE in Mathematics A Linear', 
		'AQA Level 1 or Level 2 GCSE in Mathematics B Modular', 
		'OCR Level 1 or Level 2 GCSE in Mathematics A Linear', 
		'OCR Level 1 or Level 2 GCSE in Mathematics B Modular', 
		'EDEXCEL Level 1 or Level 2 GCSE in Mathematics A Linear', 
		'EDEXCEL Level 1 or Level 2 GCSE in Mathematics B Modular', 
		'WJEC Level 1 or Level 2 GCSE in Mathematics', 
		'OCR Level 1 or Level 2 GCSE in Mathematics C', 
		'AQA Level 1 or Level 2 GCSE in Mathematics Pilot', 
		'AQA Level 1 or Level 2 GCSE in Additional Mathematics Pilot', 
		'OCR Level 1 or Level 2 GCSE in Mathematics D Pilot', 
		'OCR Level 1 or Level 2 GCSE in Additional Mathematics Pilot', 
		'WJEC Level 1 or Level 2 GCSE in Additional Mathematics Pilot', 
		'OCR Level 3 Advanced Subsidiary GCE in Mathematics Pilot', 
		'AQA Level 3 Advanced Subsidiary GCE in Mathematics Pilot', 
		'OCR Level 1 or Level 2 GCSE in Mathematics Pilot', 
		'Cambridge International Level 1 or Level 2 Certificate in Mathematics', 
		'OCR Level 1 or Level 2 GCSE in Mathematics A', 
		'OCR Level 1 or Level 2 GCSE in Applications of Mathematics Pilot', 
		'WJEC Level 1 or Level 2 GCSE in Mathematics', 
		'AQA Level 1 or Level 2 GCSE in Mathematics', 
		'OCR Level 1 or Level 2 GCSE in Methods in Mathematics Pilot', 
		'Pearson Edexcel Level 1 or Level 2 GCSE in Mathematics B', 
		'Pearson Edexcel Level 1 or Level 2 GCSE in Mathematics A', 
		'OCR Level 1 or Level 2 GCSE in Mathematics B', 
		'CCEA Level 1 or Level 2 GCSE in Mathematics', 
		'AQA Level 1 or Level 2 GCSE in Applications of Mathematics Pilot', 
		'Pearson Edexcel Level 1 or Level 2 GCSE in Applications of Mathematics Pilot', 
		'AQA Level 1 or Level 2 GCSE in Methods in Mathematics Pilot', 
		'Pearson Edexcel Level 1 or Level 2 GCSE in Methods in Mathematics Pilot', 
		'AQA Level 1 or Level 2 GCSE in Mathematics B', 
		'WJEC Level 1 or Level 2 GCSE in Mathematics - Linear', 
		'Pearson Edexcel Level 1 or Level 2 Certificate in Mathematics', 
		'AQA Level 2 Certificate in Further Mathematics', 
		'Edexcel IGCSE Mathematics']
		
				eng_lit = ['AQA Level 3 Advanced Subsidiary GCE in English Literature B', 
		'OCR Level 3 Advanced Subsidiary GCE in English Literature', 
		'CCEA Level 3 Advanced Subsidiary GCE in English Literature', 
		'AQA Level 3 Advanced Subsidiary GCE in English Literature A', 
		'Pearson Edexcel Level 3 Advanced Subsidiary GCE in English Literature', 
		'WJEC Level 3 Advanced Subsidiary GCE in English Literature', 
		'Cambridge International Level 1 or Level 2 Certificate in Literature English', 
		'WJEC Level 1 or Level 2 GCSE in English Literature', 
		'Pearson Edexcel Level 1 or Level 2 GCSE in English Literature', 
		'AQA Level 1 or Level 2 GCSE in English Literature', 
		'OCR Level 1 or Level 2 GCSE in English Literature', 
		'CCEA Level 1 or Level 2 GCSE in English Literature', 
		'Pearson Edexcel Level 1 or Level 2 Certificate in English Literature', 
		'WJEC Level 1 or  Level 2 Certificate in English Literature', 
		'AQA Level 1 or 2 Certificate in English Literature', 
		'AQA Level 1 or Level 2 GCSE in English Literature', 
		'Pearson Edexcel Level 1 or Level 2 GCSE in English Literature', 
		'AQA Level 1 or Level 2 GCSE in English Literature', 
		'WJEC Level 1 or Level 2 GCSE in English Literature', 
		'OCR Level 1 or Level 2 GCSE in English Literature']
		
		eng = ['AQA Level 1 or Level 2 GCSE in English A', 
		'AQA Level 1 or Level 2 GCSE in English B', 
		'OCR Level 1 or Level 2 GCSE in English', 
		'WJEC Level 1 or Level 2 GCSE in English', 
		'EDEXCEL Level 1 or Level 2 GCSE in English A', 
		'EDEXCEL Level 1 or Level 2 GCSE in English B', 
		'CCEA Level 1 or Level 2 GCSE in English', 
		'EDEXCEL Level 1 or Level 2 GCSE in English Single Award Pilot', 
		'EDEXCEL Level 1 or Level 2 GCSE in English Double Award Pilot', 
		'AQA Level 3 Advanced Subsidiary GCE in English Language B', 
		'AQA Level 3 Advanced Subsidiary GCE in English Language A', 
		'OCR Level 3 Advanced Subsidiary GCE in English Language', 
		'Pearson Edexcel Level 3 Advanced Subsidiary GCE in English Language', 
		'WJEC Level 3 Advanced Subsidiary GCE in English Language', 
		'Cambridge International Level 1 or Level 2 Certificate in First Language English', 
		'Pearson Edexcel Level 1 or Level 2 GCSE in English Language', 
		'Pearson Edexcel Level 1 or Level 2 GCSE in English', 
		'WJEC Level 1 or Level 2 GCSE in English Language', 
		'OCR Level 1 or Level 2 GCSE in English', 
		'WJEC Level 1 or Level 2 GCSE in English', 
		'AQA Level 1 or Level 2 GCSE in English', 
		'AQA Level 1 or Level 2 GCSE in English Language', 
		'OCR Level 1 or Level 2 GCSE in English Language', 
		'CCEA Level 1 or Level 2 GCSE in English Language', 
		'CCEA Level 1 or Level 2 GCSE in English', 
		'Pearson Level 1 or Level 2 Certificate in English Language', 
		'WJEC Level 1 or  Level 2 Certificate in English Language', 
		'AQA Level 1 or 2 Certificate in English Language', 
		'WJEC Level 1 or Level 2 GCSE in English', 
		'WJEC Level 1 or Level 2 GCSE in English Language', 
		'Pearson Edexcel Level 1 or Level 2 GCSE in English', 
		'Pearson Edexcel Level 1 or Level 2 GCSE in English Language', 
		'AQA Level 1 or Level 2 GCSE in English', 
		'AQA Level 1 or Level 2 GCSE in English Language', 
		'OCR Level 1 or 2 GCSE in English Language', 
		'OCR Level 1 or 2 GCSE in English', 
		'Edexcel IGCSE English Language'];
		science =['CCEA Level 1 or Level 2 GCSE in Science: Single Award', 
		'CCEA Level 1 or Level 2 GCSE in Biology', 
		'CCEA Level 1 or Level 2 GCSE in Chemistry', 
		'CCEA Level 1 or Level 2 GCSE in Physics', 
		'Pearson Edexcel Level 1 or Level 2 GCSE in Science', 
		'Pearson Edexcel Level 1 or Level 2 GCSE in Additional Science', 
		'Pearson Edexcel Level 1 or Level 2 GCSE in Biology', 
		'Pearson Edexcel Level 1 or Level 2 GCSE in Chemistry', 
		'Pearson Edexcel Level 1 or Level 2 GCSE in Physics', 
		'AQA Level 1 or Level 2 GCSE in Additional Science', 
		'AQA Level 1 or Level 2 GCSE in Science B', 
		'AQA Level 1 or Level 2 GCSE in Science A', 
		'AQA Level 1 or Level 2 GCSE in Physics', 
		'AQA Level 1 or Level 2 GCSE in Biology', 
		'AQA Level 1 or Level 2 GCSE in Chemistry', 
		'OCR Level 1 or Level 2 GCSE in Science A', 
		'OCR Level 1 or Level 2 GCSE in Additional Science A', 
		'OCR Level 1 or Level 2 GCSE in Biology A', 
		'OCR Level 1 or Level 2 GCSE in Physics A', 
		'OCR Level 1 or Level 2 GCSE in Chemistry A', 
		'OCR Level 1 or Level 2 GCSE in Science B', 
		'OCR Level 1 or Level 2 GCSE in Additional Science B', 
		'OCR Level 1 or Level 2 GCSE in Physics B', 
		'OCR Level 1 or Level 2 GCSE in Biology B', 
		'OCR Level 1 or Level 2 GCSE in Chemistry B', 
		'WJEC Level 1 or Level 2 GCSE in Science', 
		'WJEC Level 1 or Level 2 GCSE in Additional Science', 
		'WJEC Level 1 or Level 2 GCSE in Biology', 
		'WJEC Level 1 or Level 2 GCSE in Physics', 
		'WJEC Level 1 or Level 2 GCSE in Chemistry', 
		'CCEA Level 1 or Level 2 GCSE in Science', 
		'OCR Level 3 Advanced Subsidiary GCE in Chemistry B', 
		'OCR Level 3 Advanced Subsidiary GCE in Physics B', 
		'OCR Level 3 Advanced Subsidiary GCE in Biology', 
		'AQA Level 3 Advanced Subsidiary GCE in Biology', 
		'OCR Level 3 Advanced Subsidiary GCE in Chemistry A', 
		'CCEA Level 3 Advanced Subsidiary GCE in Physics', 
		'CCEA Level 3 Advanced Subsidiary GCE in Chemistry', 
		'CCEA Level 3 Advanced Subsidiary GCE in Biology', 
		'Pearson Edexcel Level 3 Advanced Subsidiary GCE in Chemistry', 
		'Pearson Level 3 Advanced Subsidiary GCE in Physics', 
		'AQA Level 3 Advanced Subsidiary GCE in Physics A', 
		'AQA Level 3 Advanced Subsidiary GCE in Physics B: Physics in Context', 
		'OCR Level 3 Advanced Subsidiary GCE in Physics A', 
		'Pearson Edexcel Level 3 Advanced Subsidiary GCE in Biology', 
		'AQA Level 3 Advanced Subsidiary GCE in Chemistry', 
		'WJEC Level 3 Advanced Subsidiary GCE in Physics', 
		'WJEC Level 3 Advanced Subsidiary GCE in Biology', 
		'WJEC Level 3 Advanced Subsidiary GCE in Chemistry', 
		'Cambridge International Level 1 or Level 2 Certificate in Physics', 
		'Cambridge International Level 1 or Level 2 Certificate in Chemistry', 
		'Cambridge International Level 1 or Level 2 Certificate in Biology', 
		'OCR Level 1 or Level 2 GCSE in Computing', 
		'Pearson Edexcel Level 1 or 2 GCSE In Biology', 
		'Pearson Edexcel Level 1 or 2 GCSE In Physics', 
		'Pearson Edexcel Level 1 or 2 GCSE In Science', 
		'AQA Level 1 or Level 2 GCSE in Science B Science in Context', 
		'Pearson Edexcel Level 1 or 2 GCSE In Additional Science', 
		'Pearson Edexcel Level 1 or 2 GCSE In Chemistry', 
		'AQA Level 1 or Level 2 GCSE in Additional science', 
		'AQA Level 1 or Level 2 GCSE in Biology', 
		'AQA Level 1 or Level 2 GCSE in Chemistry', 
		'AQA Level 1 or Level 2 GCSE in Physics', 
		'AQA Level 1 or Level 2 GCSE in Science A', 
		'WJEC Level 1 or Level 2 GCSE in Additional Science', 
		'WJEC Level 1 or Level 2 GCSE in Biology', 
		'WJEC Level 1 or Level 2 GCSE in Science B', 
		'WJEC Level 1 or Level 2 GCSE in Physics', 
		'WJEC Level 1 or Level 2 GCSE in Chemistry', 
		'WJEC Level 1 or Level 2 GCSE in Science A', 
		'OCR Level 1 or Level 2 GCSE in Chemistry B', 
		'OCR Level 1 or Level 2 GCSE in Physics A', 
		'CCEA Level 1 or Level 2 GCSE in Physics', 
		'OCR Level 1 or Level 2 GCSE in Physics B', 
		'OCR Level 1 or Level 2 GCSE in Additional Science B', 
		'OCR Level 1 or Level 2 GCSE in Biology A', 
		'OCR Level 1 or Level 2 GCSE in Biology B', 
		'OCR Level 1 or Level 2 GCSE in Science B', 
		'CCEA Level 1 or Level 2 GCSE in Single Award Science', 
		'OCR Level 1 or Level 2 GCSE in Additional Science A', 
		'OCR Level 1 or Level 2 GCSE in Chemistry A', 
		'OCR Level 1 or Level 2 GCSE in Science A', 
		'Pearson Edexcel Level 1 or Level 2 Certificate in Chemistry', 
		'Pearson Edexcel Level 1 or Level 2 Certificate in Biology', 
		'Pearson Edexcel Level 1 or Level 2 Certificate in Physics', 
		'Pearson Edexcel Level 1 or Level 2 Certificate in Science Double Award', 
		'AQA Level 1 or 2 Certificate in Biology', 
		'AQA Level 1 or 2 Certificate in Chemistry', 
		'AQA Level 1 or 2 Certificate in Physics', 
		'AQA Level 1 or 2 GCSE in Computer Science', 
		'WJEC Level 1 or Level 2 GCSE in Computer Science', 
		'CCEA Level 1 or 2 GCSE in Science Single Award', 
		'AQA Level 1 or 2 Certificate in Science: Double Award', 
		'Pearson Edexcel Level 1 or Level 2 GCSE in Computer Science', 
		'AQA Level 3 Advanced Subsidiary GCE in Biology', 
		'Edexcel IGCSE Biology', 
		'Edexcel IGCSE Chemistry', 
		'Edexcel IGCSE Physics', 'Edexcel IGCSE Science Double Award'];
		humanities = ['OCR Level 3 Advanced Subsidiary GCE in History B',
		'Pearson Edexcel Level 3 Advanced Subsidiary GCE in History',
		'Pearson Edexcel Level 3 Advanced Subsidiary GCE in Geography',
		'OCR Level 3 Advanced Subsidiary GCE in History A',
		'AQA Level 3 Advanced Subsidiary GCE in History',
		'CCEA Level 3 Advanced Subsidiary GCE in History',
		'CCEA Level 3 Advanced Subsidiary GCE in Geography',
		'AQA Level 3 Advanced Subsidiary GCE in Geography',
		'OCR Level 3 Advanced Subsidiary GCE in Geography',
		'OCR Level 3 Advanced Subsidiary GCE in Classics: Ancient History',
		'WJEC Level 3 Advanced Subsidiary GCE in History',
		'WJEC Level 3 Advanced Subsidiary GCE in Geography',
		'OCR Level 1 or Level 2 GCSE in Ancient History',
		'CCEA Level 1 or Level 2 GCSE in Geography',
		'Pearson Edexcel Level 1 or Level 2 GCSE in History A',
		'Pearson Edexcel Level 1 or Level 2 GCSE in History B',
		'AQA Level 1 or Level 2 GCSE in History B',
		'OCR Level 1 or Level 2 GCSE in History A',
		'OCR Level 1 or Level 2 GCSE in Geography B',
		'AQA Level 1 or Level 2 GCSE in History A',
		'WJEC Level 1 or Level 2 GCSE in Geography A',
		'AQA Level 1 or Level 2 GCSE in Geography A',
		'WJEC Level 1 or Level 2 GCSE in History',
		'WJEC Level 1 or Level 2 GCSE in Geography B',
		'OCR Level 1 or Level 2 GCSE in History B',
		'AQA Level 1 or Level 2 GCSE in Geography B',
		'Pearson Edexcel Level 1 or Level 2 GCSE in Geography A',
		'Pearson Edexcel Level 1 or Level 2 GCSE in Geography B',
		'OCR Level 1 or Level 2 GCSE in Geography A',
		'Cambridge International Level 1 or Level 2 Certificate in Geography',
		'Cambridge International Level 1 or Level 2 Certificate in History',
		'Pearson Edexcel Level 1 or 2 Certificate in Geography',
		'Pearson Edexcel Level 1 or Level 2 Certificate in History',
		'AQA Level 1 or 2 Certificate in History',
		'AQA Level 1 or 2 Certificate in Geography',
		'WJEC Level 1 or Level 2 GCSE in Geography A',
		'AQA Level 1 or Level 2 GCSE in Geography A',
		'WJEC Level 1 or Level 2 GCSE in Geography B',
		'Pearson Edexcel Level 1 or Level 2 GCSE in Geography A',
		'CCEA Level 1 or 2 GCSE in Geography B',
		'OCR Level 1 or Level 2 GCSE in Geography B',
		'Pearson Edexcel Level 1 or Level 2 GCSE in Geography B',
		'AQA Level 1 or Level 2 GCSE in Geography B',
		'AQA Level 1 or Level 2 GCSE in History B',
		'OCR Level 1 or Level 2 GCSE in Geography A',
		'AQA Level 1 or Level 2 GCSE in History A',
		'WJEC Level 1 or Level 2 GCSE in History',
		'Pearson Edexcel Level 1 or Level 2 GCSE in History A',
		'Pearson Edexcel Level 1 or Level 2 GCSE in History B',
		'AQA Level 1 or Level 2 GCSE in History A',
		'AQA Level 1 or Level 2 GCSE in History B',
		'OCR Level 1 or Level 2 GCSE in History A',
		'OCR Level 1 or Level 2 GCSE in History B',
		'Edexcel IGCSE Geography',
		'Edexcel IGCSE History'];
		 lang = ['CCEA Level 1 or Level 2 GCSE in Gaeilge',
		'WJEC Level 1 or Level 2 GCSE in Welsh: First Language',
		'WJEC Level 1 or Level 2 GCSE in Welsh Second Language',
		'AQA Level 3 Advanced Subsidiary GCE in Spanish',
		'AQA Level 3 Advanced Subsidiary GCE in German',
		'AQA Level 3 Advanced Subsidiary GCE in French',
		'OCR Level 3 Advanced Subsidiary GCE in Spanish',
		'OCR Level 3 Advanced Subsidiary GCE in French',
		'OCR Level 3 Advanced Subsidiary GCE in German',
		'OCR Level 3 Advanced Subsidiary GCE in Biblical Hebrew',
		'AQA Level 3 Advanced Subsidiary GCE in Polish',
		'AQA Level 3 Advanced Subsidiary GCE in Panjabi',
		'AQA Level 3 Advanced Subsidiary GCE in Modern Hebrew',
		'AQA Level 3 Advanced Subsidiary GCE in Bengali',
		'OCR Level 3 Advanced Subsidiary GCE in Persian',
		'OCR Level 3 Advanced Subsidiary GCE in Turkish',
		'OCR Level 3 Advanced Subsidiary GCE in Portuguese',
		'OCR Level 3 Advanced Subsidiary GCE in Dutch',
		'OCR Level 3 Advanced Subsidiary GCE in Gujarati',
		'Pearson Edexcel Level 3 Advanced Subsidiary GCE in Japanese',
		'Pearson Edexcel Level 3 Advanced Subsidiary GCE in Arabic',
		'Pearson Edexcel Level 3 Advanced Subsidiary GCE in Greek',
		'CCEA Level 3 Advanced Subsidiary GCE in French',
		'CCEA Level 3 Advanced Subsidiary GCE in Spanish',
		'CCEA Level 3 Advanced Subsidiary GCE in Irish',
		'CCEA Level 3 Advanced Subsidiary GCE in German',
		'OCR Level 3 Advanced Subsidiary GCE in Classics: Classical Greek',
		'OCR Level 3 Advanced Subsidiary GCE in Classics: Latin',
		'Pearson Edexcel Level 3 Advanced Subsidiary GCE in Russian',
		'Pearson Edexcel Level 3 Advanced Subsidiary GCE in French',
		'Pearson Edexcel Level 3 Advanced Subsidiary GCE in Italian',
		'Pearson Edexcel Level 3 Advanced Subsidiary GCE in Spanish',
		'Pearson Edexcel Level 3 Advanced Subsidiary GCE in Urdu',
		'Pearson Edexcel Level 3 Advanced Subsidiary GCE in German',
		'Pearson Edexcel Level 3 Advanced Subsidiary GCE in Chinese',
		'WJEC Level 3 Advanced Subsidiary GCE in French',
		'WJEC Level 3 Advanced Subsidiary GCE in German',
		'WJEC Level 3 Advanced Subsidiary GCE in Spanish',
		'WJEC Level 3 Advanced Subsidiary GCE in Cymraeg Iaith Gyntaf',
		'WJEC Level 3 Advanced Subsidiary GCE in Cymraeg Ail Iaith',
		'CCEA Level 1 or Level 2 GCSE in Irish',
		'AQA Level 1 or Level 2 GCSE in German',
		'OCR Level 1 or Level 2 GCSE in Biblical Hebrew',
		'Pearson Edexcel Level 1 or Level 2 GCSE in Greek',
		'Pearson Edexcel Level 1 or Level 2 GCSE in Japanese',
		'CCEA Level 1 or Level 2 GCSE in German',
		'CCEA Level 1 or Level 2 GCSE in French',
		'CCEA Level 1 or Level 2 GCSE in Spanish',
		'Pearson Edexcel Level 1 or Level 2 GCSE in Arabic',
		'AQA Level 1 or Level 2 GCSE in French',
		'Pearson Edexcel Level 1 or Level 2 GCSE in Russian',
		'AQA Level 1 or Level 2 GCSE in Italian',
		'AQA Level 1 or Level 2 GCSE in Spanish',
		'OCR Level 1 or Level 2 GCSE in French',
		'AQA Level 1 or Level 2 GCSE in Chinese Mandarin',
		'AQA Level 1 or Level 2 GCSE in Urdu',
		'OCR Level 1 or Level 2 GCSE in Spanish',
		'OCR Level 1 or Level 2 GCSE in German',
		'WJEC Level 1 or Level 2 GCSE in German',
		'OCR Level 1 or Level 2 GCSE in Latin',
		'WJEC Level 1 or Level 2 GCSE in French',
		'WJEC Level 1 or Level 2 GCSE in Spanish',
		'Pearson Edexcel Level 1 or Level 2 GCSE in German',
		'Pearson Edexcel Level 1 or Level 2 GCSE in Italian',
		'Pearson Edexcel Level 1 or Level 2 GCSE in Spanish',
		'Pearson Edexcel Level 1 or Level 2 GCSE in French',
		'Pearson Edexcel Level 1 or Level 2 GCSE in Urdu',
		'AQA Level 1 or Level 2 GCSE in Modern Hebrew',
		'AQA Level 1 or Level 2 GCSE in Panjabi',
		'AQA Level 1 or Level 2 GCSE in Polish',
		'AQA Level 1 or Level 2 GCSE in Bengali',
		'OCR Level 1 or Level 2 GCSE in Classical Greek',
		'Pearson Edexcel Level 1 or Level 2 GCSE in Chinese',
		'OCR Level 1 or Level 2 GCSE in Persian',
		'OCR Level 1 or Level 2 GCSE in Turkish',
		'OCR Level 1 or Level 2 GCSE in Portuguese',
		'OCR Level 1 or Level 2 GCSE in Gujarati',
		'OCR Level 1 or Level 2 GCSE in Dutch',
		'Cambridge International Level 1 or Level 2 Certificate in French',
		'Cambridge International Level 1 or Level 2 Certificate in Greek',
		'WJEC Level 2 Certificate in Latin Language',
		'WJEC Level 2 Certificate in Latin Language and Roman Civilisation',
		'CCEA Level 1 or Level 2 GCSE in Gaeilge',
		'Cambridge International Level 1 or Level 2 Certificate in German',
		'Cambridge International Level 1 or Level 2 Certificate in Spanish',
		'Cambridge International Level 1 or Level 2 Certificate in Mandarin Chinese',
		'Pearson Edexcel Level 1 or Level 2 Certificate in Chinese',
		'Pearson Edexcel Level 1 or Level 2 Certificate in French',
		'Pearson Edexcel Level 1 or Level 2 Certificate in Spanish',
		'Pearson Edexcel Level 1 or Level 2 Certificate in German',
		'AQA Level 1 or 2 Certificate in French',
		'AQA Level 1 or 2 Certificate in German',
		'AQA Level 1 or 2 Certificate in Spanish',
		'CIE IGCSE German ',
		'CIE IGCSE Spanish ',
		'CIE IGCSE Chinese Mandarin'];
		other =["Pearson BTEC Level 1 or Level 2 First Certificate in Art and Design", 
		"Pearson BTEC Level 1 or Level 2 First Extended Certificate in Art and Design", 
		"Pearson BTEC Level 1 or Level 2 First Diploma in Art and Design", 
		"Pearson BTEC Level 1 or Level 2 First Certificate in Business", 
		"Pearson BTEC Level 1 or Level 2 First Extended Certificate in Business", 
		"Pearson BTEC Level 1 or Level 2 First Diploma in Business", 
		"Pearson BTEC Level 1 or Level 2 First Certificate in Children's Play, Learning and Development", 
		"City & Guilds Level 2 Principal Learning in Construction and the Built Environment", 
		"Pearson BTEC Level 1 or Level 2 First Certificate in Construction and the Built Environment", 
		"Pearson BTEC Level 1 or Level 2 First Extended Certificate in Construction and the Built Environment", 
		"Pearson BTEC Level 1 or Level 2 First Diploma in Construction and the Built Environment", 
		"City & Guilds Level 2 Certificate in Mechanical Engineering QCF", 
		"City & Guilds Level 2 Diploma in Mechanical Engineering QCF", 
		"City & Guilds Level 2 Principal Learning in Engineering", 
		"EAL level 2 First Diploma in Engineering Technology †", 
		"IMIAL Level 2 Diploma in Service and Maintenance Engineering VRQ", 
		"Pearson BTEC Level 1 or Level 2 First Certificate in Engineering", 
		"Pearson BTEC Level 1 or Level 2 First Extended Certificate in Engineering", 
		"Pearson Edexcel Level 2 Principal Learning in Engineering", 
		"Pearson BTEC Level 1 or Level 2 First Diploma in Engineering", 
		"City & Guilds Level 2 Principal Learning in Hair and Beauty Studies", 
		"VTCT Level 2 Principal Learning in Hair and Beauty Studies", 
		"Pearson BTEC Level 1 or Level 2 First Certificate in Health and Social Care", 
		"Pearson BTEC Level 1 or Level 2 First Extended Certificate in Health and Social Care", 
		"Pearson BTEC Level 1 or Level 2 First Diploma in Health and Social Care", 
		"Pearson BTEC Level 1 or Level 2 First Certificate in Hospitality", 
		"Pearson BTEC Level 1 or Level 2 First Extended Certificate in Hospitality", 
		"Pearson BTEC Level 1 or Level 2 First Diploma in Hospitality", 
		"Pearson BTEC Level 1 or Level 2 First Certificate in Information and Creative Technology", 
		"Pearson BTEC Level 1 or Level 2 First Extended Certificate in Information and Creative Technology", 
		"Pearson BTEC Level 1 or Level 2 First Diploma in Information and Creative Technology", 
		"Pearson BTEC Level 1 or Level 2 First Certificate in Creative Digital Media Production", 
		"Pearson BTEC Level 1 or Level 2 First Extended Certificate in Creative Digital Media Production", 
		"Pearson BTEC Level 1 or Level 2 First Diploma in Creative Digital Media Production", 
		"Pearson BTEC Level 1 or Level 2 First Certificate in Performing Arts", 
		"Pearson BTEC Level 1 or Level 2 First Extended Certificate in Performing Arts", 
		"Pearson BTEC Level 1 or Level 2 First Diploma in Performing Arts", 
		"Pearson BTEC Level 1 or Level 2 First Certificate in Music", 
		"Pearson BTEC Level 1 or Level 2 First Extended Certificate in Music", 
		"Pearson BTEC Level 1 or Level 2 First Diploma in Music", 
		"Pearson BTEC Level 1 or Level 2 First Extended Certificate in Applied Science", 
		"Pearson BTEC Level 1 or Level 2 First Certificate in Sport", 
		"Pearson BTEC Level 1 or Level 2 First Extended Certificate in Sport", 
		"Pearson BTEC Level 1 or Level 2 First Diploma in Sport", 
		"VTCT Level 2 Principal Learning in Sport and Active Leisure", 
		"Pearson BTEC Level 1 or Level 2 First Certificate in Travel and Tourism", 
		"Pearson BTEC Level 1 or Level 2 First Extended Certificate in Travel and Tourism", 
		"Pearson BTEC Level 1 or Level 2 First Diploma in Travel and Tourism", 
		"Pearson BTEC Level 1 Diploma in Business Administration QCF", 
		"Pearson BTEC Level 1 Diploma in Art and Design QCF", 
		"Pearson BTEC Level 1 Diploma in Caring for Children QCF", 
		"City & Guilds Level 1 Principal Learning in Construction and the Built Environment", 
		"Pearson BTEC Level 1 Extended Certificate In Construction QCF", 
		"Pearson BTEC Level 1 Diploma in Construction QCF", 
		"Pearson BTEC Level 1 Diploma in Engineering QCF", 
		"IMIAL Level 1 Diploma in Service and Maintenance Engineering VRQ", 
		"VTCT Level 1 Principal Learning in Hair and Beauty Studies", 
		"City & Guilds Level 1 Principal Learning in Hair and Beauty Studies", 
		"Pearson BTEC Level 1 Diploma in Health and Social Care QCF", 
		"Pearson BTEC Level 1 Diploma in Exploring the Caring Sectors QCF", 
		"Pearson BTEC Level 1 Diploma for IT Users ITQ QCF", 
		"Pearson BTEC Level 1 Extended Certificate in Creative Media Production QCF", 
		"Pearson BTEC Level 1 Diploma in Creative Media Production QCF", 
		"Pearson BTEC Level 1 Diploma in Performing Arts QCF", 
		"Pearson BTEC Level 1 Diploma in Applied Science QCF", 
		"Pearson BTEC Level 1 Diploma in Sport and Active Leisure QCF", 
		"VTCT Level 1 Principal Learning in Sport and Active Leisure", 
		"Pearson BTEC Level 1 Diploma in Introduction to the Travel and Tourism Industry QCF", 
		"OCR Level 1 or 2 Certificate in Applied History", 
		"OCR Level 1 or 2 Certificate in Living Texts", 
		"WJEC Level 2 Certificate in Latin Literature", 
		"WJEC Level 1 Certificate in Latin Language", 
		"WJEC Level 1 Certificate in Latin Language and Roman Civilisation", 
		"WJEC Level 1 Certificate in Latin Literature", 
		"AQA Level 1 or Level 2 Certificate in use of Mathematics"];
	
		#Checking Arrays to see if the subject is in each one
			if maths.include? subject_title 
				return 'maths'
			elsif eng_lit.include? subject_title
				return 'english_lit'
			elsif eng.include? subject_title
				return 'english'
			elsif science.include? subject_title
				return 'science'
			elsif humanities.include? subject_title
				 'humanities'
			elsif lang.include? subject_title
				return 'language'
			elsif other.include? subject_title
				return 'other'
			else 
				return false
			end
	end
end
